### ISSUE TITLE
how to use this

### ISSUE THREAD

**Issue by vtolstov** [dan-compton/grpc-gateway-cors#1]
Hi. I'm need CORS with grpc-gateway and found this package, but where i can find api/credentials/credentials.proto ? and How to generate pb.go files (which cmd to protoc ?)

**Comment by vtolstov** [comment]
And does it possible to provide CORS pers service ?
As i understand wrap can be used in grpc-gateway only for all

**Comment by vtolstov** [comment]
?

**Comment by albttx** [comment]
I found information here
https://github.com/dan-compton/grpc-gateway-cors/blob/master/protoc-gen-grpc-gateway-cors/main.go#L5

A better README explanation might be cool

**Comment by albttx** [comment]
But i didn't to make it work too ...

**Comment by dan-compton** [comment]
Hey guys, I've been on vacation and job hunting.  I'll provide an example in my monorepo github.com/dan-compton/world

**Comment by dan-compton** [comment]
A cleaned up version of this will be contributed upstream.  I'm archiving this repository.
